language: python

python:
  - "2.7.15"
  
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script: 
  - cd api/app
  - nosetests test_views.py --with-coverage --cover-package=app

after_success:
  - coveralls
  