oclanguage: python

python:
	- "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"

script: 
        python run.py
        pytest 

after_success:
  - coveralls
  

