language: python

python:
  - "2.7.15"
  
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script: 
  - cd api/app
  - nosetests --with-coverage

after_success:
  - coveralls
  