language: python

python:
	- '2.7.15'

install:
  - pip install -r requirements.txt
  - pip install pytest-travis-fold
  - pip install coverage
  - pip install coveralls

script: 
  - py.test 

after_success:
  - coveralls
  
